### ISSUE TITLE
Sensor module. Sensor can't be started

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/octopus-telemetry#154]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
The DVL should start when pressing the button.

## Current Behavior
The DVL isn't starting and the button aren't actuating anything

## Environment Used
- Project version : Latest develop branch used for the telemetry

**Comment by supertoto29** [comment]
![Screenshot from 2022-05-28 11-40-10](https://user-images.githubusercontent.com/44241055/170832437-f7ad1e47-c21f-40eb-b3ca-bac97c5d1ed9.png)
![Screenshot from 2022-05-28 11-40-32](https://user-images.githubusercontent.com/44241055/170832440-79686c5a-51f9-466e-acf9-8c6caad8efc0.png)
@Kam0ss

**Comment by Kam0ss** [comment]
Ok, can you try to start/stop the DVL and watch what is going on on rostopic /provider_dvl/enable_disable_ping ?
And if everything seems to be normal, you can try to open the telemetry container and try to put false instead of true here : https://github.com/sonia-auv/octopus-telemetry/blob/742208f129c6c62f86d96d77e0c981d7b06cd91b/src/components/ControlModule.tsx#L232

**Comment by Kam0ss** [comment]
Did that work ?

**Comment by supertoto29** [comment]
We did not have time to test it. This will need to be tested this week.
